---

- hosts: webservers
  gather_facts: no 

  collections:
    - community.general 

  roles:
    - name: DataDog.datadog
      become: yes   

  vars:
      datadog_api_key: "{{ vault_dd_api_key }}" 

      