---

- hosts: webservers
  gather_facts: no

  # pre_tasks:
  #   - name: copy requirements.yml to server
  #     ansible.builtin.template:
  #       src: ../requirements.yml
  #       dest: /home/kate/requirements.yml
  #     become: yes  
  #   - name: execute ansible install roles
  #     ansible.builtin.shell: ansible-galaxy install -r requirements.yml  

  collections:
    - community.general 

  roles:
    - name: DataDog.datadog
      become: yes   

  vars:
      datadog_api_key: "{{ DATADOG_API_KEY }}" 

      